/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MediasRouteImport } from './routes/medias'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as DiplomesRouteImport } from './routes/diplomes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BiographieRouteImport } from './routes/biographie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MediasRoute = MediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const DiplomesRoute = DiplomesRouteImport.update({
  id: '/diplomes',
  path: '/diplomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographieRoute = BiographieRouteImport.update({
  id: '/biographie',
  path: '/biographie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biographie': typeof BiographieRoute
  '/contact': typeof ContactRoute
  '/diplomes': typeof DiplomesRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/medias': typeof MediasRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biographie': typeof BiographieRoute
  '/contact': typeof ContactRoute
  '/diplomes': typeof DiplomesRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/medias': typeof MediasRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biographie': typeof BiographieRoute
  '/contact': typeof ContactRoute
  '/diplomes': typeof DiplomesRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/medias': typeof MediasRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biographie'
    | '/contact'
    | '/diplomes'
    | '/evenements'
    | '/formations'
    | '/medias'
    | '/services'
    | '/temoignages'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biographie'
    | '/contact'
    | '/diplomes'
    | '/evenements'
    | '/formations'
    | '/medias'
    | '/services'
    | '/temoignages'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biographie'
    | '/contact'
    | '/diplomes'
    | '/evenements'
    | '/formations'
    | '/medias'
    | '/services'
    | '/temoignages'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BiographieRoute: typeof BiographieRoute
  ContactRoute: typeof ContactRoute
  DiplomesRoute: typeof DiplomesRoute
  EvenementsRoute: typeof EvenementsRoute
  FormationsRoute: typeof FormationsRoute
  MediasRoute: typeof MediasRoute
  ServicesRoute: typeof ServicesRoute
  TemoignagesRoute: typeof TemoignagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medias': {
      id: '/medias'
      path: '/medias'
      fullPath: '/medias'
      preLoaderRoute: typeof MediasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diplomes': {
      id: '/diplomes'
      path: '/diplomes'
      fullPath: '/diplomes'
      preLoaderRoute: typeof DiplomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biographie': {
      id: '/biographie'
      path: '/biographie'
      fullPath: '/biographie'
      preLoaderRoute: typeof BiographieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BiographieRoute: BiographieRoute,
  ContactRoute: ContactRoute,
  DiplomesRoute: DiplomesRoute,
  EvenementsRoute: EvenementsRoute,
  FormationsRoute: FormationsRoute,
  MediasRoute: MediasRoute,
  ServicesRoute: ServicesRoute,
  TemoignagesRoute: TemoignagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
